### ISSUE TITLE
Make OSEPs into directory rather than files

### ISSUE THREAD

**Issue by rufuspollock** [openspending/osep#15]
e.g.

```
/osep-01.md => /osep-01/index.md
```

Why: we can put images for a given OSEP in osep directory and similarly with other relates files (e.g. example code etc).

**Comment by pwalsh** [comment]
I looked into this when we last talked about it. Because of Jekyll's seemingly arbitrary restrictions on inclusion, it is not possible to include files or other resources from directory unless:
- It is the `_includes` directory, via the `{% include %}` tag
- It is a post in the `_posts` directory, in which case you can use `{% include_relative %}` (No - it doesn't even work with collections, _only_ `_posts`)

So, that is why I used `_includes` [here](https://github.com/openspending/osep/tree/gh-pages/_includes) for OSEP-04.

I am referring to includes at render time - I don't know about static resources like images, so I'll check that.

**Comment by rufuspollock** [comment]
I got you but you can still leave stuff in the _includes that you need to and we can still have the directories.
