### ISSUE TITLE
[OSEP-03] Flask web framework

### ISSUE THREAD

**Issue by pwalsh** [openspending/osep#5]
Comments for [OSEP-03](http://labs.openspending.org/osep/03-flask-web-framework.html)

**Comment by rufuspollock** [comment]
I feel we should either accept this OSEP (we do want to use Flask instead of Pylons) or close as Invalid since we have a new more partitioned architecture. My sense is that we should accept in that Flask is our default python webapp library going forward and do we plan to migrate off pylons.

@tryggvib @pwalsh wdyt?

**Comment by pwalsh** [comment]
I think it definitely should be accepted, and possibly a bit of rewording before hand, like, the bottom line proposal is:

OpenSpending microservices will by default be build on Flask. In specific cases, other frameworks/languages **may** be considered, but only if (a) the nature of the problem merits a different solution (a convincing case must be made), and (b) consideration has been made for additional overhead/costs around integration with rest of ecosystem.

**Comment by pwalsh** [comment]
OSEP-03 is now accepted, so I'm closing the discussion thread to reduce noise on the issue tracker. Of course, anyone can still comment.

OSEP-03 has been around for some time, and simply declares the base assumption that Flask will be our go-to framework for OpenSpending. So, I accepted it as is.
